version: "3.1"

services:
  postgres:
    container_name: db_web_parking
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      POSTGRES_DB: web_parking
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  storage_db: